name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: 'hello-python:1.0'

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}
    - name: Login to DockerHub
      if: ${{ job.status }}
      uses: docker/login-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}
    - name: Push image to DockerHub
      if: ${{ job.status }}
      run: docker push ${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}
      

